//	Lootspawner junction list for buildings to classes
//	Author: Na_Palm (BIS forums)
//-------------------------------------------------------------------------------------
//"Buildingstoloot_list" array of [buildingname, class]
//								buildingname: 	building class name (in editor debug console use "typeof BIS_fnc_camera_target"
//												to monitor and then copy/paste or any other method you know...)
//								class: 			0-civil, 1-military, ... (add more as you wish)
//
//!!!EVERY building must have only ONE entry here AND been in ONE class!!!
//-------------------------------------------------------------------------------------
Buildingstoloot_list = [

["Land_Airport_left_F", 0],
["Land_Airport_right_F", 0],
["Land_Airport_Tower_dam_F", 2],
["Land_Airport_Tower_F", 2],
["Land_cargo_house_slum_F", 0],
["Land_Cargo_House_V1_F", 1],
["Land_Cargo_House_V2_F", 1],
["Land_Cargo_House_V3_F", 1],
["Land_Cargo_HQ_V1_F", 1],
["Land_Cargo_HQ_V2_F", 1],
["Land_Cargo_HQ_V3_F", 1],
["Land_Cargo_Patrol_V1_F", 1],
["Land_Cargo_Patrol_V2_F", 1],
["Land_Cargo_Patrol_V3_F", 1],
["Land_Cargo_Tower_V1_F", 1],
["Land_Cargo_Tower_V3_F", 1],
["Land_CarService_F", 2],
["Land_Chapel_Small_V1_F", 0],
["Land_Chapel_Small_V2_F", 0],
["Land_Chapel_V1_F", 0],
["Land_Chapel_V2_F", 0],
["Land_Crane_F", 0],
["Land_dp_bigTank_F", 2], 
["Land_dp_mainFactory_F", 2],
["Land_d_Stone_Shed_V1_F", 0], 
["Land_d_Windmill01_F", 0],
["Land_FuelStation_Build_F", 0], 
["Land_FuelStation_Shed_F", 0], 
["Land_Hangar_F", 2],
["Land_Hospital_main_F", 0],
["Land_Hospital_side1_F", 0],
["Land_Hospital_side2_F", 0],
["Land_i_Addon_02_V1_F", 0],
["Land_i_Addon_03mid_V1_F", 0], 
["Land_i_Addon_03_V1_F", 0], 
["Land_i_Addon_04_V1_F", 0], 
["Land_i_Barracks_V1_F", 2],
["Land_i_Barracks_V2_F", 1],
["Land_i_Garage_V1_F", 0], 
["Land_i_Garage_V2_F", 0],
["Land_i_House_Big_01_V1_dam_F", 0], 
["Land_i_House_Big_01_V1_F", 0], 
["Land_i_House_Big_01_V2_F", 0],
["Land_i_House_Big_01_V3_F", 0],
["Land_i_House_Big_02_V1_dam_F", 0], 
["Land_i_House_Big_02_V1_F", 0], 
["Land_i_House_Big_02_V2_F", 0],
["Land_i_House_Big_02_V3_F", 0],
["Land_i_House_Small_01_V1_dam_F", 0], 
["Land_i_House_Small_01_V1_F", 0], 
["Land_i_House_Small_01_V2_dam_F", 0], 
["Land_i_House_Small_01_V2_F", 0], 
["Land_i_House_Small_01_V3_F", 0],
["Land_i_House_Small_02_V1_dam_F", 0], 
["Land_i_House_Small_02_V1_F", 0], 
["Land_i_House_Small_02_V2_F", 0],
["Land_i_House_Small_02_V3_F", 0],
["Land_i_House_Small_03_V1_dam_F", 0], 
["Land_i_House_Small_03_V1_F", 0], 
["Land_i_Shed_Ind_F", 2],
["Land_i_Shop_01_V1_dam_F", 0], 
["Land_i_Shop_01_V1_F", 0], 
["Land_i_Shop_01_V2_F", 0],
["Land_i_Shop_01_V3_F", 0],
["Land_i_Shop_02_V1_dam_F", 0], 
["Land_i_Shop_02_V1_F", 0], 
["Land_i_Shop_02_V2_F", 0],
["Land_i_Shop_02_V3_F", 0],
["Land_i_Stone_HouseBig_V1_dam_F", 0], 
["Land_i_Stone_HouseBig_V1_F", 0], 
["Land_i_Stone_HouseBig_V2_F", 0],
["Land_i_Stone_HouseBig_V3_F", 0],
["Land_i_Stone_HouseSmall_V1_dam_F", 0], 
["Land_i_Stone_HouseSmall_V1_F", 0], 
["Land_i_Stone_HouseSmall_V2_F", 0],
["Land_i_Stone_HouseSmall_V3_F", 0],
["Land_i_Stone_Shed_V1_dam_F", 0], 
["Land_i_Stone_Shed_V1_F", 0], 
["Land_i_Stone_Shed_V2_F", 0],
["Land_i_Stone_Shed_V3_F", 0],
["Land_i_Windmill01_F", 0],
["Land_LightHouse_F", 0], 
["Land_Lighthouse_small_F", 0], 
["Land_Metal_Shed_F", 2], 
["Land_MilOffices_V1_F", 1],
["Land_Offices_01_V1_F", 0],
["Land_Radar_F", 2],
["Land_Research_house_V1_F", 3],
["Land_Research_HQ_F", 3],
["Land_Slum_House01_F", 0],
["Land_Slum_House02_F", 0],
["Land_Slum_House03_F", 0],
["Land_spp_Tower_F", 2],
["Land_Unfinished_Building_01_F", 2], 
["Land_Unfinished_Building_02_F", 2],
["Land_u_Addon_01_V1_F", 0], 
["Land_u_Addon_02_V1_F", 0], 
["Land_u_Barracks_V2_F", 1],
["Land_u_House_Big_01_V1_F", 0],
["Land_u_House_Big_02_V1_F", 0],
["Land_u_House_Small_01_V1_dam_F", 0], 
["Land_u_House_Small_01_V1_F", 0], 
["Land_u_House_Small_02_V1_dam_F", 0], 
["Land_u_House_Small_02_V1_F", 0], 
["Land_u_Shed_Ind_F", 2],
["Land_u_Shop_01_V1_F", 0],
["Land_u_Shop_02_V1_F", 0],
["Land_WIP_F", 2],
//costum buildings
["Land_bo_Panelak2", 0],
["Land_bo_Panelak", 0],
["Land_bo_A_GeneralStore_01", 0],
["Land_bo_Sara_domek_sedy", 0],
["Land_bo_HouseV_2T2", 0],
["Land_bo_HouseB_Tenement", 0],
["Land_bo_Dum_mesto2", 0],
["Land_bo_Shed_Ind02", 0],
["Land_bo_Barn_W_02", 0],
["Land_bo_stodola_old_open", 0],
["Land_bo_Barn_W_01", 2],
["Land_bo_HouseV_1I4", 0]
];